// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: plugin/proto/orbis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{0}
}

type GameManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomDef             `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Entities      []*EntityDef           `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	Commands      []*CommandDef          `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameManifest) Reset() {
	*x = GameManifest{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameManifest) ProtoMessage() {}

func (x *GameManifest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameManifest.ProtoReflect.Descriptor instead.
func (*GameManifest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{1}
}

func (x *GameManifest) GetRooms() []*RoomDef {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GameManifest) GetEntities() []*EntityDef {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *GameManifest) GetCommands() []*CommandDef {
	if x != nil {
		return x.Commands
	}
	return nil
}

type RoomDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Exits         map[string]string      `protobuf:"bytes,6,rep,name=exits,proto3" json:"exits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ChildIds      []string               `protobuf:"bytes,7,rep,name=child_ids,json=childIds,proto3" json:"child_ids,omitempty"` // entity IDs that start in this room
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDef) Reset() {
	*x = RoomDef{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDef) ProtoMessage() {}

func (x *RoomDef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDef.ProtoReflect.Descriptor instead.
func (*RoomDef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{2}
}

func (x *RoomDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoomDef) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *RoomDef) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *RoomDef) GetExits() map[string]string {
	if x != nil {
		return x.Exits
	}
	return nil
}

func (x *RoomDef) GetChildIds() []string {
	if x != nil {
		return x.ChildIds
	}
	return nil
}

type EntityDef struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Aliases            []string               `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Tags               []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Fields             map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // field_name → JSON value e.g. "42", "\"hello\"", "true"
	ContainerId        string                 `protobuf:"bytes,7,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`                                              // parent container entity ID (for nested entities like box contents)
	ContainerComponent string                 `protobuf:"bytes,8,opt,name=container_component,json=containerComponent,proto3" json:"container_component,omitempty"`                         // "Container" or "Inventory"
	HasInventory       bool                   `protobuf:"varint,9,opt,name=has_inventory,json=hasInventory,proto3" json:"has_inventory,omitempty"`                                          // entity has an Inventory component
	HasContainer       bool                   `protobuf:"varint,10,opt,name=has_container,json=hasContainer,proto3" json:"has_container,omitempty"`                                         // entity has a Container component
	ContainerPrefix    string                 `protobuf:"bytes,11,opt,name=container_prefix,json=containerPrefix,proto3" json:"container_prefix,omitempty"`                                 // prefix string for container
	ContainerRevealed  bool                   `protobuf:"varint,12,opt,name=container_revealed,json=containerRevealed,proto3" json:"container_revealed,omitempty"`                          // initial revealed state
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EntityDef) Reset() {
	*x = EntityDef{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDef) ProtoMessage() {}

func (x *EntityDef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDef.ProtoReflect.Descriptor instead.
func (*EntityDef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{3}
}

func (x *EntityDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityDef) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EntityDef) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *EntityDef) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EntityDef) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *EntityDef) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *EntityDef) GetContainerComponent() string {
	if x != nil {
		return x.ContainerComponent
	}
	return ""
}

func (x *EntityDef) GetHasInventory() bool {
	if x != nil {
		return x.HasInventory
	}
	return false
}

func (x *EntityDef) GetHasContainer() bool {
	if x != nil {
		return x.HasContainer
	}
	return false
}

func (x *EntityDef) GetContainerPrefix() string {
	if x != nil {
		return x.ContainerPrefix
	}
	return ""
}

func (x *EntityDef) GetContainerRevealed() bool {
	if x != nil {
		return x.ContainerRevealed
	}
	return false
}

type CommandDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Aliases       []string               `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Patterns      []*CommandPattern      `protobuf:"bytes,3,rep,name=patterns,proto3" json:"patterns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDef) Reset() {
	*x = CommandDef{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDef) ProtoMessage() {}

func (x *CommandDef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDef.ProtoReflect.Descriptor instead.
func (*CommandDef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{4}
}

func (x *CommandDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandDef) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *CommandDef) GetPatterns() []*CommandPattern {
	if x != nil {
		return x.Patterns
	}
	return nil
}

type CommandPattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Syntax        string                 `protobuf:"bytes,1,opt,name=syntax,proto3" json:"syntax,omitempty"`
	NoMatch       string                 `protobuf:"bytes,2,opt,name=no_match,json=noMatch,proto3" json:"no_match,omitempty"`
	Help          string                 `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandPattern) Reset() {
	*x = CommandPattern{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandPattern) ProtoMessage() {}

func (x *CommandPattern) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandPattern.ProtoReflect.Descriptor instead.
func (*CommandPattern) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{5}
}

func (x *CommandPattern) GetSyntax() string {
	if x != nil {
		return x.Syntax
	}
	return ""
}

func (x *CommandPattern) GetNoMatch() string {
	if x != nil {
		return x.NoMatch
	}
	return ""
}

func (x *CommandPattern) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // template ID of the reacting entity
	Source        *EntitySnapshot        `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Target        *EntitySnapshot        `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Instrument    *EntitySnapshot        `protobuf:"bytes,5,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Room          *EntitySnapshot        `protobuf:"bytes,6,opt,name=room,proto3" json:"room,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{6}
}

func (x *EventRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *EventRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *EventRequest) GetSource() *EntitySnapshot {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *EventRequest) GetTarget() *EntitySnapshot {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EventRequest) GetInstrument() *EntitySnapshot {
	if x != nil {
		return x.Instrument
	}
	return nil
}

func (x *EventRequest) GetRoom() *EntitySnapshot {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *EventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EntitySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Aliases       []string               `protobuf:"bytes,4,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // same encoding as EntityDef.fields
	Children      []*ChildRef            `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`                                                                       // immediate children across all components
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySnapshot) Reset() {
	*x = EntitySnapshot{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySnapshot) ProtoMessage() {}

func (x *EntitySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySnapshot.ProtoReflect.Descriptor instead.
func (*EntitySnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{7}
}

func (x *EntitySnapshot) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *EntitySnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntitySnapshot) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EntitySnapshot) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *EntitySnapshot) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EntitySnapshot) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *EntitySnapshot) GetChildren() []*ChildRef {
	if x != nil {
		return x.Children
	}
	return nil
}

type ChildRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Component     string                 `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"` // "Room", "Inventory", "Container"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildRef) Reset() {
	*x = ChildRef{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildRef) ProtoMessage() {}

func (x *ChildRef) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildRef.ProtoReflect.Descriptor instead.
func (*ChildRef) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{8}
}

func (x *ChildRef) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ChildRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChildRef) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ChildRef) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type EngineUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineUpdate) Reset() {
	*x = EngineUpdate{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineUpdate) ProtoMessage() {}

func (x *EngineUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineUpdate.ProtoReflect.Descriptor instead.
func (*EngineUpdate) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{9}
}

func (x *EngineUpdate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ActionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionList) Reset() {
	*x = ActionList{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionList) ProtoMessage() {}

func (x *ActionList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionList.ProtoReflect.Descriptor instead.
func (*ActionList) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{10}
}

func (x *ActionList) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Action_Print
	//	*Action_Publish
	//	*Action_Move
	//	*Action_SetField
	//	*Action_Destroy
	//	*Action_Spawn
	//	*Action_After
	//	*Action_Reveal
	//	*Action_Hide
	Kind          isAction_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{11}
}

func (x *Action) GetKind() isAction_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Action) GetPrint() *PrintAction {
	if x != nil {
		if x, ok := x.Kind.(*Action_Print); ok {
			return x.Print
		}
	}
	return nil
}

func (x *Action) GetPublish() *PublishAction {
	if x != nil {
		if x, ok := x.Kind.(*Action_Publish); ok {
			return x.Publish
		}
	}
	return nil
}

func (x *Action) GetMove() *MoveAction {
	if x != nil {
		if x, ok := x.Kind.(*Action_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *Action) GetSetField() *SetFieldAction {
	if x != nil {
		if x, ok := x.Kind.(*Action_SetField); ok {
			return x.SetField
		}
	}
	return nil
}

func (x *Action) GetDestroy() *DestroyAction {
	if x != nil {
		if x, ok := x.Kind.(*Action_Destroy); ok {
			return x.Destroy
		}
	}
	return nil
}

func (x *Action) GetSpawn() *SpawnAction {
	if x != nil {
		if x, ok := x.Kind.(*Action_Spawn); ok {
			return x.Spawn
		}
	}
	return nil
}

func (x *Action) GetAfter() *AfterAction {
	if x != nil {
		if x, ok := x.Kind.(*Action_After); ok {
			return x.After
		}
	}
	return nil
}

func (x *Action) GetReveal() *RevealAction {
	if x != nil {
		if x, ok := x.Kind.(*Action_Reveal); ok {
			return x.Reveal
		}
	}
	return nil
}

func (x *Action) GetHide() *HideAction {
	if x != nil {
		if x, ok := x.Kind.(*Action_Hide); ok {
			return x.Hide
		}
	}
	return nil
}

type isAction_Kind interface {
	isAction_Kind()
}

type Action_Print struct {
	Print *PrintAction `protobuf:"bytes,1,opt,name=print,proto3,oneof"`
}

type Action_Publish struct {
	Publish *PublishAction `protobuf:"bytes,2,opt,name=publish,proto3,oneof"`
}

type Action_Move struct {
	Move *MoveAction `protobuf:"bytes,3,opt,name=move,proto3,oneof"`
}

type Action_SetField struct {
	SetField *SetFieldAction `protobuf:"bytes,4,opt,name=set_field,json=setField,proto3,oneof"`
}

type Action_Destroy struct {
	Destroy *DestroyAction `protobuf:"bytes,5,opt,name=destroy,proto3,oneof"`
}

type Action_Spawn struct {
	Spawn *SpawnAction `protobuf:"bytes,6,opt,name=spawn,proto3,oneof"`
}

type Action_After struct {
	After *AfterAction `protobuf:"bytes,7,opt,name=after,proto3,oneof"`
}

type Action_Reveal struct {
	Reveal *RevealAction `protobuf:"bytes,8,opt,name=reveal,proto3,oneof"`
}

type Action_Hide struct {
	Hide *HideAction `protobuf:"bytes,9,opt,name=hide,proto3,oneof"`
}

func (*Action_Print) isAction_Kind() {}

func (*Action_Publish) isAction_Kind() {}

func (*Action_Move) isAction_Kind() {}

func (*Action_SetField) isAction_Kind() {}

func (*Action_Destroy) isAction_Kind() {}

func (*Action_Spawn) isAction_Kind() {}

func (*Action_After) isAction_Kind() {}

func (*Action_Reveal) isAction_Kind() {}

func (*Action_Hide) isAction_Kind() {}

// role values: "source", "target", "instrument", "room"
type PrintAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintAction) Reset() {
	*x = PrintAction{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintAction) ProtoMessage() {}

func (x *PrintAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintAction.ProtoReflect.Descriptor instead.
func (*PrintAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{12}
}

func (x *PrintAction) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PrintAction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ExcludeRoles  []string               `protobuf:"bytes,2,rep,name=exclude_roles,json=excludeRoles,proto3" json:"exclude_roles,omitempty"` // roles to exclude from broadcast
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishAction) Reset() {
	*x = PublishAction{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAction) ProtoMessage() {}

func (x *PublishAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAction.ProtoReflect.Descriptor instead.
func (*PublishAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{13}
}

func (x *PublishAction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublishAction) GetExcludeRoles() []string {
	if x != nil {
		return x.ExcludeRoles
	}
	return nil
}

type MoveAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityRole    string                 `protobuf:"bytes,1,opt,name=entity_role,json=entityRole,proto3" json:"entity_role,omitempty"`          // which entity to move
	DestRole      string                 `protobuf:"bytes,2,opt,name=dest_role,json=destRole,proto3" json:"dest_role,omitempty"`                // destination entity
	DestComponent string                 `protobuf:"bytes,3,opt,name=dest_component,json=destComponent,proto3" json:"dest_component,omitempty"` // "Room", "Inventory", "Container"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveAction) Reset() {
	*x = MoveAction{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveAction) ProtoMessage() {}

func (x *MoveAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveAction.ProtoReflect.Descriptor instead.
func (*MoveAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{14}
}

func (x *MoveAction) GetEntityRole() string {
	if x != nil {
		return x.EntityRole
	}
	return ""
}

func (x *MoveAction) GetDestRole() string {
	if x != nil {
		return x.DestRole
	}
	return ""
}

func (x *MoveAction) GetDestComponent() string {
	if x != nil {
		return x.DestComponent
	}
	return ""
}

type SetFieldAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                          // JSON-encoded
	ValueType     string                 `protobuf:"bytes,4,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"` // "int", "string", "bool"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFieldAction) Reset() {
	*x = SetFieldAction{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFieldAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFieldAction) ProtoMessage() {}

func (x *SetFieldAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFieldAction.ProtoReflect.Descriptor instead.
func (*SetFieldAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{15}
}

func (x *SetFieldAction) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SetFieldAction) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SetFieldAction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetFieldAction) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

type DestroyAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyAction) Reset() {
	*x = DestroyAction{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyAction) ProtoMessage() {}

func (x *DestroyAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyAction.ProtoReflect.Descriptor instead.
func (*DestroyAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{16}
}

func (x *DestroyAction) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SpawnAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	DestRole      string                 `protobuf:"bytes,2,opt,name=dest_role,json=destRole,proto3" json:"dest_role,omitempty"`
	DestComponent string                 `protobuf:"bytes,3,opt,name=dest_component,json=destComponent,proto3" json:"dest_component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnAction) Reset() {
	*x = SpawnAction{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnAction) ProtoMessage() {}

func (x *SpawnAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnAction.ProtoReflect.Descriptor instead.
func (*SpawnAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{17}
}

func (x *SpawnAction) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SpawnAction) GetDestRole() string {
	if x != nil {
		return x.DestRole
	}
	return ""
}

func (x *SpawnAction) GetDestComponent() string {
	if x != nil {
		return x.DestComponent
	}
	return ""
}

type AfterAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelayMs       int64                  `protobuf:"varint,1,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	Actions       []*Action              `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterAction) Reset() {
	*x = AfterAction{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterAction) ProtoMessage() {}

func (x *AfterAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterAction.ProtoReflect.Descriptor instead.
func (*AfterAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{18}
}

func (x *AfterAction) GetDelayMs() int64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *AfterAction) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type RevealAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealAction) Reset() {
	*x = RevealAction{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealAction) ProtoMessage() {}

func (x *RevealAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealAction.ProtoReflect.Descriptor instead.
func (*RevealAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{19}
}

func (x *RevealAction) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RevealAction) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

type HideAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Component     string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HideAction) Reset() {
	*x = HideAction{}
	mi := &file_plugin_proto_orbis_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HideAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HideAction) ProtoMessage() {}

func (x *HideAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_orbis_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HideAction.ProtoReflect.Descriptor instead.
func (*HideAction) Descriptor() ([]byte, []int) {
	return file_plugin_proto_orbis_proto_rawDescGZIP(), []int{20}
}

func (x *HideAction) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *HideAction) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

var File_plugin_proto_orbis_proto protoreflect.FileDescriptor

const file_plugin_proto_orbis_proto_rawDesc = "" +
	"\n" +
	"\x18plugin/proto/orbis.proto\x12\x05orbis\"\a\n" +
	"\x05Empty\"\x91\x01\n" +
	"\fGameManifest\x12$\n" +
	"\x05rooms\x18\x01 \x03(\v2\x0e.orbis.RoomDefR\x05rooms\x12,\n" +
	"\bentities\x18\x02 \x03(\v2\x10.orbis.EntityDefR\bentities\x12-\n" +
	"\bcommands\x18\x03 \x03(\v2\x11.orbis.CommandDefR\bcommands\"\x81\x02\n" +
	"\aRoomDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12/\n" +
	"\x05exits\x18\x06 \x03(\v2\x19.orbis.RoomDef.ExitsEntryR\x05exits\x12\x1b\n" +
	"\tchild_ids\x18\a \x03(\tR\bchildIds\x1a8\n" +
	"\n" +
	"ExitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x03\n" +
	"\tEntityDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x124\n" +
	"\x06fields\x18\x06 \x03(\v2\x1c.orbis.EntityDef.FieldsEntryR\x06fields\x12!\n" +
	"\fcontainer_id\x18\a \x01(\tR\vcontainerId\x12/\n" +
	"\x13container_component\x18\b \x01(\tR\x12containerComponent\x12#\n" +
	"\rhas_inventory\x18\t \x01(\bR\fhasInventory\x12#\n" +
	"\rhas_container\x18\n" +
	" \x01(\bR\fhasContainer\x12)\n" +
	"\x10container_prefix\x18\v \x01(\tR\x0fcontainerPrefix\x12-\n" +
	"\x12container_revealed\x18\f \x01(\bR\x11containerRevealed\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\n" +
	"CommandDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaliases\x18\x02 \x03(\tR\aaliases\x121\n" +
	"\bpatterns\x18\x03 \x03(\v2\x15.orbis.CommandPatternR\bpatterns\"W\n" +
	"\x0eCommandPattern\x12\x16\n" +
	"\x06syntax\x18\x01 \x01(\tR\x06syntax\x12\x19\n" +
	"\bno_match\x18\x02 \x01(\tR\anoMatch\x12\x12\n" +
	"\x04help\x18\x03 \x01(\tR\x04help\"\x9f\x02\n" +
	"\fEventRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12-\n" +
	"\x06source\x18\x03 \x01(\v2\x15.orbis.EntitySnapshotR\x06source\x12-\n" +
	"\x06target\x18\x04 \x01(\v2\x15.orbis.EntitySnapshotR\x06target\x125\n" +
	"\n" +
	"instrument\x18\x05 \x01(\v2\x15.orbis.EntitySnapshotR\n" +
	"instrument\x12)\n" +
	"\x04room\x18\x06 \x01(\v2\x15.orbis.EntitySnapshotR\x04room\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"\xb8\x02\n" +
	"\x0eEntitySnapshot\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\aaliases\x18\x04 \x03(\tR\aaliases\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x129\n" +
	"\x06fields\x18\x06 \x03(\v2!.orbis.EntitySnapshot.FieldsEntryR\x06fields\x12+\n" +
	"\bchildren\x18\a \x03(\v2\x0f.orbis.ChildRefR\bchildren\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\bChildRef\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1c\n" +
	"\tcomponent\x18\x04 \x01(\tR\tcomponent\"\"\n" +
	"\fEngineUpdate\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"5\n" +
	"\n" +
	"ActionList\x12'\n" +
	"\aactions\x18\x01 \x03(\v2\r.orbis.ActionR\aactions\"\xaf\x03\n" +
	"\x06Action\x12*\n" +
	"\x05print\x18\x01 \x01(\v2\x12.orbis.PrintActionH\x00R\x05print\x120\n" +
	"\apublish\x18\x02 \x01(\v2\x14.orbis.PublishActionH\x00R\apublish\x12'\n" +
	"\x04move\x18\x03 \x01(\v2\x11.orbis.MoveActionH\x00R\x04move\x124\n" +
	"\tset_field\x18\x04 \x01(\v2\x15.orbis.SetFieldActionH\x00R\bsetField\x120\n" +
	"\adestroy\x18\x05 \x01(\v2\x14.orbis.DestroyActionH\x00R\adestroy\x12*\n" +
	"\x05spawn\x18\x06 \x01(\v2\x12.orbis.SpawnActionH\x00R\x05spawn\x12*\n" +
	"\x05after\x18\a \x01(\v2\x12.orbis.AfterActionH\x00R\x05after\x12-\n" +
	"\x06reveal\x18\b \x01(\v2\x13.orbis.RevealActionH\x00R\x06reveal\x12'\n" +
	"\x04hide\x18\t \x01(\v2\x11.orbis.HideActionH\x00R\x04hideB\x06\n" +
	"\x04kind\";\n" +
	"\vPrintAction\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\rPublishAction\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rexclude_roles\x18\x02 \x03(\tR\fexcludeRoles\"q\n" +
	"\n" +
	"MoveAction\x12\x1f\n" +
	"\ventity_role\x18\x01 \x01(\tR\n" +
	"entityRole\x12\x1b\n" +
	"\tdest_role\x18\x02 \x01(\tR\bdestRole\x12%\n" +
	"\x0edest_component\x18\x03 \x01(\tR\rdestComponent\"o\n" +
	"\x0eSetFieldAction\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"value_type\x18\x04 \x01(\tR\tvalueType\"#\n" +
	"\rDestroyAction\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"r\n" +
	"\vSpawnAction\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1b\n" +
	"\tdest_role\x18\x02 \x01(\tR\bdestRole\x12%\n" +
	"\x0edest_component\x18\x03 \x01(\tR\rdestComponent\"Q\n" +
	"\vAfterAction\x12\x19\n" +
	"\bdelay_ms\x18\x01 \x01(\x03R\adelayMs\x12'\n" +
	"\aactions\x18\x02 \x03(\v2\r.orbis.ActionR\aactions\"@\n" +
	"\fRevealAction\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\">\n" +
	"\n" +
	"HideAction\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent2\xaf\x01\n" +
	"\tOrbisGame\x120\n" +
	"\vGetManifest\x12\f.orbis.Empty\x1a\x13.orbis.GameManifest\x125\n" +
	"\vHandleEvent\x12\x13.orbis.EventRequest\x1a\x11.orbis.ActionList\x129\n" +
	"\vEventStream\x12\x13.orbis.EngineUpdate\x1a\x11.orbis.ActionList(\x010\x01B\x1eZ\x1cexample.com/mud/plugin/protob\x06proto3"

var (
	file_plugin_proto_orbis_proto_rawDescOnce sync.Once
	file_plugin_proto_orbis_proto_rawDescData []byte
)

func file_plugin_proto_orbis_proto_rawDescGZIP() []byte {
	file_plugin_proto_orbis_proto_rawDescOnce.Do(func() {
		file_plugin_proto_orbis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_orbis_proto_rawDesc), len(file_plugin_proto_orbis_proto_rawDesc)))
	})
	return file_plugin_proto_orbis_proto_rawDescData
}

var file_plugin_proto_orbis_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_plugin_proto_orbis_proto_goTypes = []any{
	(*Empty)(nil),          // 0: orbis.Empty
	(*GameManifest)(nil),   // 1: orbis.GameManifest
	(*RoomDef)(nil),        // 2: orbis.RoomDef
	(*EntityDef)(nil),      // 3: orbis.EntityDef
	(*CommandDef)(nil),     // 4: orbis.CommandDef
	(*CommandPattern)(nil), // 5: orbis.CommandPattern
	(*EventRequest)(nil),   // 6: orbis.EventRequest
	(*EntitySnapshot)(nil), // 7: orbis.EntitySnapshot
	(*ChildRef)(nil),       // 8: orbis.ChildRef
	(*EngineUpdate)(nil),   // 9: orbis.EngineUpdate
	(*ActionList)(nil),     // 10: orbis.ActionList
	(*Action)(nil),         // 11: orbis.Action
	(*PrintAction)(nil),    // 12: orbis.PrintAction
	(*PublishAction)(nil),  // 13: orbis.PublishAction
	(*MoveAction)(nil),     // 14: orbis.MoveAction
	(*SetFieldAction)(nil), // 15: orbis.SetFieldAction
	(*DestroyAction)(nil),  // 16: orbis.DestroyAction
	(*SpawnAction)(nil),    // 17: orbis.SpawnAction
	(*AfterAction)(nil),    // 18: orbis.AfterAction
	(*RevealAction)(nil),   // 19: orbis.RevealAction
	(*HideAction)(nil),     // 20: orbis.HideAction
	nil,                    // 21: orbis.RoomDef.ExitsEntry
	nil,                    // 22: orbis.EntityDef.FieldsEntry
	nil,                    // 23: orbis.EntitySnapshot.FieldsEntry
}
var file_plugin_proto_orbis_proto_depIdxs = []int32{
	2,  // 0: orbis.GameManifest.rooms:type_name -> orbis.RoomDef
	3,  // 1: orbis.GameManifest.entities:type_name -> orbis.EntityDef
	4,  // 2: orbis.GameManifest.commands:type_name -> orbis.CommandDef
	21, // 3: orbis.RoomDef.exits:type_name -> orbis.RoomDef.ExitsEntry
	22, // 4: orbis.EntityDef.fields:type_name -> orbis.EntityDef.FieldsEntry
	5,  // 5: orbis.CommandDef.patterns:type_name -> orbis.CommandPattern
	7,  // 6: orbis.EventRequest.source:type_name -> orbis.EntitySnapshot
	7,  // 7: orbis.EventRequest.target:type_name -> orbis.EntitySnapshot
	7,  // 8: orbis.EventRequest.instrument:type_name -> orbis.EntitySnapshot
	7,  // 9: orbis.EventRequest.room:type_name -> orbis.EntitySnapshot
	23, // 10: orbis.EntitySnapshot.fields:type_name -> orbis.EntitySnapshot.FieldsEntry
	8,  // 11: orbis.EntitySnapshot.children:type_name -> orbis.ChildRef
	11, // 12: orbis.ActionList.actions:type_name -> orbis.Action
	12, // 13: orbis.Action.print:type_name -> orbis.PrintAction
	13, // 14: orbis.Action.publish:type_name -> orbis.PublishAction
	14, // 15: orbis.Action.move:type_name -> orbis.MoveAction
	15, // 16: orbis.Action.set_field:type_name -> orbis.SetFieldAction
	16, // 17: orbis.Action.destroy:type_name -> orbis.DestroyAction
	17, // 18: orbis.Action.spawn:type_name -> orbis.SpawnAction
	18, // 19: orbis.Action.after:type_name -> orbis.AfterAction
	19, // 20: orbis.Action.reveal:type_name -> orbis.RevealAction
	20, // 21: orbis.Action.hide:type_name -> orbis.HideAction
	11, // 22: orbis.AfterAction.actions:type_name -> orbis.Action
	0,  // 23: orbis.OrbisGame.GetManifest:input_type -> orbis.Empty
	6,  // 24: orbis.OrbisGame.HandleEvent:input_type -> orbis.EventRequest
	9,  // 25: orbis.OrbisGame.EventStream:input_type -> orbis.EngineUpdate
	1,  // 26: orbis.OrbisGame.GetManifest:output_type -> orbis.GameManifest
	10, // 27: orbis.OrbisGame.HandleEvent:output_type -> orbis.ActionList
	10, // 28: orbis.OrbisGame.EventStream:output_type -> orbis.ActionList
	26, // [26:29] is the sub-list for method output_type
	23, // [23:26] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_plugin_proto_orbis_proto_init() }
func file_plugin_proto_orbis_proto_init() {
	if File_plugin_proto_orbis_proto != nil {
		return
	}
	file_plugin_proto_orbis_proto_msgTypes[11].OneofWrappers = []any{
		(*Action_Print)(nil),
		(*Action_Publish)(nil),
		(*Action_Move)(nil),
		(*Action_SetField)(nil),
		(*Action_Destroy)(nil),
		(*Action_Spawn)(nil),
		(*Action_After)(nil),
		(*Action_Reveal)(nil),
		(*Action_Hide)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_orbis_proto_rawDesc), len(file_plugin_proto_orbis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_orbis_proto_goTypes,
		DependencyIndexes: file_plugin_proto_orbis_proto_depIdxs,
		MessageInfos:      file_plugin_proto_orbis_proto_msgTypes,
	}.Build()
	File_plugin_proto_orbis_proto = out.File
	file_plugin_proto_orbis_proto_goTypes = nil
	file_plugin_proto_orbis_proto_depIdxs = nil
}
