// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: plugin/proto/orbis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrbisGame_GetManifest_FullMethodName = "/orbis.OrbisGame/GetManifest"
	OrbisGame_HandleEvent_FullMethodName = "/orbis.OrbisGame/HandleEvent"
	OrbisGame_EventStream_FullMethodName = "/orbis.OrbisGame/EventStream"
)

// OrbisGameClient is the client API for OrbisGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrbisGameClient interface {
	GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GameManifest, error)
	HandleEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*ActionList, error)
	EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EngineUpdate, ActionList], error)
}

type orbisGameClient struct {
	cc grpc.ClientConnInterface
}

func NewOrbisGameClient(cc grpc.ClientConnInterface) OrbisGameClient {
	return &orbisGameClient{cc}
}

func (c *orbisGameClient) GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GameManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameManifest)
	err := c.cc.Invoke(ctx, OrbisGame_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbisGameClient) HandleEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*ActionList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionList)
	err := c.cc.Invoke(ctx, OrbisGame_HandleEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orbisGameClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EngineUpdate, ActionList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrbisGame_ServiceDesc.Streams[0], OrbisGame_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EngineUpdate, ActionList]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrbisGame_EventStreamClient = grpc.BidiStreamingClient[EngineUpdate, ActionList]

// OrbisGameServer is the server API for OrbisGame service.
// All implementations must embed UnimplementedOrbisGameServer
// for forward compatibility.
type OrbisGameServer interface {
	GetManifest(context.Context, *Empty) (*GameManifest, error)
	HandleEvent(context.Context, *EventRequest) (*ActionList, error)
	EventStream(grpc.BidiStreamingServer[EngineUpdate, ActionList]) error
	mustEmbedUnimplementedOrbisGameServer()
}

// UnimplementedOrbisGameServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrbisGameServer struct{}

func (UnimplementedOrbisGameServer) GetManifest(context.Context, *Empty) (*GameManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedOrbisGameServer) HandleEvent(context.Context, *EventRequest) (*ActionList, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleEvent not implemented")
}
func (UnimplementedOrbisGameServer) EventStream(grpc.BidiStreamingServer[EngineUpdate, ActionList]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedOrbisGameServer) mustEmbedUnimplementedOrbisGameServer() {}
func (UnimplementedOrbisGameServer) testEmbeddedByValue()                   {}

// UnsafeOrbisGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrbisGameServer will
// result in compilation errors.
type UnsafeOrbisGameServer interface {
	mustEmbedUnimplementedOrbisGameServer()
}

func RegisterOrbisGameServer(s grpc.ServiceRegistrar, srv OrbisGameServer) {
	// If the following call panics, it indicates UnimplementedOrbisGameServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrbisGame_ServiceDesc, srv)
}

func _OrbisGame_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbisGameServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbisGame_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbisGameServer).GetManifest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbisGame_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrbisGameServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrbisGame_HandleEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrbisGameServer).HandleEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrbisGame_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrbisGameServer).EventStream(&grpc.GenericServerStream[EngineUpdate, ActionList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrbisGame_EventStreamServer = grpc.BidiStreamingServer[EngineUpdate, ActionList]

// OrbisGame_ServiceDesc is the grpc.ServiceDesc for OrbisGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrbisGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orbis.OrbisGame",
	HandlerType: (*OrbisGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _OrbisGame_GetManifest_Handler,
		},
		{
			MethodName: "HandleEvent",
			Handler:    _OrbisGame_HandleEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _OrbisGame_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin/proto/orbis.proto",
}
